name: Deploy to Droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Deploy code to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} "
          cd /var/www/myapp &&
          git pull origin main &&
          npm install &&
          pm2 restart all || pm2 start index.js --name myapp
        "
